edition = "2018"
unstable_features = true

comment_width = 100
condense_wildcard_suffixes = true
empty_item_single_line = false
format_code_in_doc_comments = true
format_strings = true
license_template_path = "license-template"
merge_imports = true
normalize_comments = false
normalize_doc_attributes = true
reorder_impl_items = true
use_field_init_shorthand = true
use_try_shorthand = true
wrap_comments = true
