name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: hecrj/setup-rust-action@v1
      with:
        rust-version: nightly
    - uses: actions/checkout@v2
      with:
        path: zical
    - name: Build
      run: cargo build --verbose

  test:
    runs-on: ubuntu-latest

    steps:
    - uses: hecrj/setup-rust-action@v1
      with:
        rust-version: nightly
    - uses: actions/checkout@v2
      with:
        path: zical
    - name: Run tests
      run: cargo test --verbose
  
  lint:
    runs-on: ubuntu-latest

    steps:
    - uses: hecrj/setup-rust-action@v1
      with:
        rust-version: nightly
        components: rustfmt
    - uses: actions/checkout@v1
      with:
        path: zical
    - name: Clippy
      run: cargo +nightly fmt -- --check

  clippy:
    runs-on: ubuntu-latest

    steps:
    - uses: hecrj/setup-rust-action@v1
      with:
        rust-version: nightly
        components: clippy
    - uses: actions/checkout@v1
      with:
        path: zical
    - name: Clippy
      run: cargo clippy -- -D warnings
