name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: hecrj/setup-rust-action@v1
      with:
        rust-version: nightly
    - uses: actions/checkout@v2
    - name: Build and Test
      run: cargo build --verbose && cargo test --verbose
  
  lint:
    runs-on: ubuntu-latest

    steps:
    - uses: hecrj/setup-rust-action@v1
      with:
        rust-version: nightly
        components: rustfmt
    - uses: actions/checkout@v1
    - name: Rustfmt
      run: cargo +nightly fmt -- --check

  clippy:
    runs-on: ubuntu-latest

    steps:
    - uses: hecrj/setup-rust-action@v1
      with:
        rust-version: nightly
        components: clippy
    - uses: actions/checkout@v1
    - name: Clippy
      run: cargo clippy -- -D warnings
