name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: hecrj/setup-rust-action@v1
      with:
        rust-version: nightly
    - uses: actions/checkout@v2
    - name: Build
      run: cd zical && cargo build --verbose

  test:
    runs-on: ubuntu-latest

    steps:
    - uses: hecrj/setup-rust-action@v1
      with:
        rust-version: nightly
    - uses: actions/checkout@v2
    - name: Run tests
      run: cd zical && cargo test --verbose
  
  lint:
    runs-on: ubuntu-latest

    steps:
    - uses: hecrj/setup-rust-action@v1
      with:
        rust-version: nightly
        components: rustfmt
    - uses: actions/checkout@v1
    - name: Clippy
      run: cd zical && cargo +nightly fmt -- --check

  clippy:
    runs-on: ubuntu-latest

    steps:
    - uses: hecrj/setup-rust-action@v1
      with:
        rust-version: nightly
        components: clippy
    - uses: actions/checkout@v1
    - name: Clippy
      run: cd zical && cargo clippy -- -D warnings
